spring:
  application:
    name: notice-message
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  cloud:
    # nacos服务端版本为2.2.0
    nacos:
      # nacos登陆账号
      username: nacos
      # nacos登陆密码
      password: dxy123
      # naocs注册中心
      discovery:
        enabled: true
        server-addr: 114.115.153.32:8848
        namespace: 6eb522cd-d12f-4d14-b4c9-7001f0499bb4
        group: ${spring.profiles.active}
        weight: 1
#Netty配置
netty:
  boss: 4
  worker: 2
  timeout: 6000
  port: 9000
  #多端口绑定
  portSalve: 9001
  host: 127.0.0.1
